/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	testistiov1 "github.com/foobarprogacct/testoperator/pkg/apis/test.istio/v1"
	versioned "github.com/foobarprogacct/testoperator/pkg/clientset/versioned"
	internalinterfaces "github.com/foobarprogacct/testoperator/pkg/informers/externalversions/internalinterfaces"
	v1 "github.com/foobarprogacct/testoperator/pkg/listers/test.istio/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TestIstioOperatorInformer provides access to a shared informer and lister for
// TestIstioOperators.
type TestIstioOperatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.TestIstioOperatorLister
}

type testIstioOperatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTestIstioOperatorInformer constructs a new informer for TestIstioOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTestIstioOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTestIstioOperatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTestIstioOperatorInformer constructs a new informer for TestIstioOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTestIstioOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestV1().TestIstioOperators(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.TestV1().TestIstioOperators(namespace).Watch(context.TODO(), options)
			},
		},
		&testistiov1.TestIstioOperator{},
		resyncPeriod,
		indexers,
	)
}

func (f *testIstioOperatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTestIstioOperatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *testIstioOperatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&testistiov1.TestIstioOperator{}, f.defaultInformer)
}

func (f *testIstioOperatorInformer) Lister() v1.TestIstioOperatorLister {
	return v1.NewTestIstioOperatorLister(f.Informer().GetIndexer())
}
