/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	testistiov1 "github.com/foobarprogacct/testoperator/pkg/apis/test.istio/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTestIstioOperators implements TestIstioOperatorInterface
type FakeTestIstioOperators struct {
	Fake *FakeTestV1
	ns   string
}

var testistiooperatorsResource = schema.GroupVersionResource{Group: "test.istio", Version: "v1", Resource: "testistiooperators"}

var testistiooperatorsKind = schema.GroupVersionKind{Group: "test.istio", Version: "v1", Kind: "TestIstioOperator"}

// Get takes name of the testIstioOperator, and returns the corresponding testIstioOperator object, and an error if there is any.
func (c *FakeTestIstioOperators) Get(ctx context.Context, name string, options v1.GetOptions) (result *testistiov1.TestIstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testistiooperatorsResource, c.ns, name), &testistiov1.TestIstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*testistiov1.TestIstioOperator), err
}

// List takes label and field selectors, and returns the list of TestIstioOperators that match those selectors.
func (c *FakeTestIstioOperators) List(ctx context.Context, opts v1.ListOptions) (result *testistiov1.TestIstioOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testistiooperatorsResource, testistiooperatorsKind, c.ns, opts), &testistiov1.TestIstioOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &testistiov1.TestIstioOperatorList{ListMeta: obj.(*testistiov1.TestIstioOperatorList).ListMeta}
	for _, item := range obj.(*testistiov1.TestIstioOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testIstioOperators.
func (c *FakeTestIstioOperators) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testistiooperatorsResource, c.ns, opts))

}

// Create takes the representation of a testIstioOperator and creates it.  Returns the server's representation of the testIstioOperator, and an error, if there is any.
func (c *FakeTestIstioOperators) Create(ctx context.Context, testIstioOperator *testistiov1.TestIstioOperator, opts v1.CreateOptions) (result *testistiov1.TestIstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testistiooperatorsResource, c.ns, testIstioOperator), &testistiov1.TestIstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*testistiov1.TestIstioOperator), err
}

// Update takes the representation of a testIstioOperator and updates it. Returns the server's representation of the testIstioOperator, and an error, if there is any.
func (c *FakeTestIstioOperators) Update(ctx context.Context, testIstioOperator *testistiov1.TestIstioOperator, opts v1.UpdateOptions) (result *testistiov1.TestIstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testistiooperatorsResource, c.ns, testIstioOperator), &testistiov1.TestIstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*testistiov1.TestIstioOperator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTestIstioOperators) UpdateStatus(ctx context.Context, testIstioOperator *testistiov1.TestIstioOperator, opts v1.UpdateOptions) (*testistiov1.TestIstioOperator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(testistiooperatorsResource, "status", c.ns, testIstioOperator), &testistiov1.TestIstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*testistiov1.TestIstioOperator), err
}

// Delete takes name of the testIstioOperator and deletes it. Returns an error if one occurs.
func (c *FakeTestIstioOperators) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testistiooperatorsResource, c.ns, name), &testistiov1.TestIstioOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestIstioOperators) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testistiooperatorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &testistiov1.TestIstioOperatorList{})
	return err
}

// Patch applies the patch and returns the patched testIstioOperator.
func (c *FakeTestIstioOperators) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *testistiov1.TestIstioOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testistiooperatorsResource, c.ns, name, pt, data, subresources...), &testistiov1.TestIstioOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*testistiov1.TestIstioOperator), err
}
